### ISSUE TITLE
use of fhir-observation-code-1 to identify observation type

### ISSUE THREAD

**Issue by agreenhalgh** [nhsconnect/FHIR-MEDICATIONS-API#10]
We'll follow the pattern used in V&M to search for a Exemption observation by specifying the fhir-observation-code-1 so we only get Exemption observations returned, as per: https://nhsconnect.github.io/visitor-and-migrants/foundations_use_case_chargeable_status_indicator.html#search-for-chargeable-status-indicator

However, the pattern to extend the fhir-observation-code-1 for each and every observation profile seems a bit awkward. Is there not a more suitable way to identify what the observation is of?

**Comment by NaminderSoorma** [comment]
completed as discussed
