### ISSUE TITLE
ValueSet: PEC Exemption Type values

### ISSUE THREAD

**Issue by agreenhalgh** [nhsconnect/FHIR-MEDICATIONS-API#2]
Please update value set to:

* `9002`: is under 16 years of age - confirmed by source
* `9003`: is 16, 17 or 18 and in full-time education - confirmed by source
* `9004`: is 60 years of age or over - confirmed by source
* `9005`: has a valid maternity exemption certificate - confirmed by source
* `9006`: has a valid medical exemption certificate - confirmed by source
* `9007`: has a valid prescription pre-payment certificate - confirmed by source
* `9008`: has a War Pension exemption certificate - confirmed by source
* `9009`: is named on a current HC2 charges certificate - confirmed by source
* `9011`: gets income support (IS) - confirmed by source
* `9012`: gets income based Job Seeker's Allowance (JSA (IB)) - confirmed by source
* `9013`: is entitled to, or named on a VALID NHS tax credit exemption certificate - confirmed by source
* `9014`: has a partner who gets Pension Credit Guarantee Credit (PGCC) - confirmed by source
* `9015`: Patient does not need to pay the prescription charge - confirmed by source

Note the following deliberately removed:
* `0000`: Patient has paid appropriate charges at old rate
* `0001`: Patient has paid appropriate charges
* `0010`: was prescribed free-of-charge contraceptives

**Comment by NaminderSoorma** [comment]
Changes have been uploaded to fhir.nhs.uk

**Comment by agreenhalgh** [comment]
Sorry I've not been clear: please get rid of 0002 to 0015, so the service will only return 9002-9999

**Comment by agreenhalgh** [comment]
valueset updated
