### ISSUE TITLE
PEC-Observation-1 dataAbsentReason invariants

### ISSUE THREAD

**Issue by agreenhalgh** [nhsconnect/FHIR-MEDICATIONS-API#4]
The invariants below don't make any sense if the dataAbsentReason and value properties are excluded in the profile: could they be got rid of.

`Constraint (obs-7): If code is the same as a component code then the value element associated with the code SHALL NOT be present
Constraint (obs-6): dataAbsentReason SHALL only be present if Observation.value[x] is not present`

**Comment by NaminderSoorma** [comment]
This will be removed from the profile to avoid confusion as we are not using it.

**Comment by NaminderSoorma** [comment]
I have researched and found it is not possible to remove these invariants as they are only for guidance as part of the Base Profile, on the differential tab they do not appear as they have in effect been profiled out.

**Comment by agreenhalgh** [comment]
Seems a bit daft but OK I'll close.
