### ISSUE TITLE
support for 'no exemption known'

### ISSUE THREAD

**Issue by agreenhalgh** [nhsconnect/FHIR-MEDICATIONS-API#5]
The service will never return a definitive 'no exemption' response, only unknown/no known exemption where no exemption is available. Would this be best conveyed by an observation with zero codes, an explicit code for 'unknown' or use of value & valueAbsentReason?

**Comment by NaminderSoorma** [comment]
As agreed in verbal discussion a code of 9999 : unknown
Will be added

**Comment by agreenhalgh** [comment]
Better:
`9999`: Not able to to be confirm exemption from source

Also need to ensure exemption observation is 1..* so that as a minimum this code is returned

**Comment by NaminderSoorma** [comment]
In the forge tool it is actually set as 1..* so it seems to be a rendering issue on the fhir server. So I will pick this up with Adam Hatherly.

**Comment by NaminderSoorma** [comment]
New value added code 9999.
