### ISSUE TITLE
014	has a partner who gets Pension Credit Guarantee Credit (PGCC)

### ISSUE THREAD

**Issue by NaminderSoorma** [nhsconnect/FHIR-MEDICATIONS-API#6]
The code for 

014 | has a partner who gets Pension Credit Guarantee Credit (PGCC)

I am querying whether the G is in the wrong order, should it read (PCGC) as an arconym?

**Comment by agreenhalgh** [comment]
That's the text taken from the HL7v3 vocab, but yeah please correct (in 9014).

**Comment by agreenhalgh** [comment]
corrected
