### ISSUE TITLE
Use Observation.code to hold fhir-observation-code-1 and store values as Observation.component

### ISSUE THREAD

**Issue by agreenhalgh** [nhsconnect/FHIR-MEDICATIONS-API#9]
Looking at the V&M pattern to use fhir-observation-code-1 we need to hold this value as Observation.code fixed to=0002, and hold values (i.e. the actual Prescription Exemptions) as Observation.components. 

For example see: https://fhir.nhs.uk/StructureDefinition/spine-vm-observation-1

**Comment by NaminderSoorma** [comment]
completed and uploaded to github/fhir.nhs.uk
